### PR TITLE
feat(msgpack): add msgpack serialization

### LINKED ISSUE #44: Use binary audio transfer instead of base64 encoding
Please try out msgpack serialisation when submitting binary audio that's currently base64 encoded. This is less efficient. PR #43 reminded me of this.

It previously wasn't possible. See upstream:
https://github.com/crossbario/autobahn-js/issues/67

See also the notes on this subject in https://build.d-centralize.nl/redmine/issues/1475
The backend supports both forms already (base64 and binary), see https://build.d-centralize.nl/redmine/projects/its-ws-server/repository/revisions/fbea39762a514a70ce8cb028d26e1ecfde53e8a7/diff

### PR DESCRIPTION
**Pull request by Lehren**
Binary audio data is serialized with msgpack

Resolves #44

### CODE REVIEW

**Comment by kvdb** [comment]
You're on fire! Nice commit. Did you actually try it out with the live backend and listen back the audio so it didn't come out scrambled?

**Comment by remcohaszing** [comment]
There's a library for encoding and decoding a Uint8Array to and from base64 (https://www.npmjs.com/package/base64-arraybuffer). I decided not to mention it before, because it was going to be refactored anyway.

Doesn't something similar exist for the new format?

**Comment by kvdb** [comment]
We don't want base64. It's not efficient. msgpack is the recommended library (according to autobahn)

**Comment by kvdb** [comment]
I'm all for merging, however, I need ack from @Lehren that it worked with our backend.

**Comment by Lehren** [comment]
This can be merged as soon as https://build.d-centralize.nl/gerrit/#/c/12549/ is merged

**Comment by joggienl** [comment]
What's the status on this PR?
It can't be merged due to conflicts. If this PR is not valid any more, please close it.

**Comment by kvdb** [comment]
It's still needed, but it also requires a change on the backend and the combination of the 2 are still not working. Not high prio, but really something to do still

**Comment by joggienl** [comment]
Closed for now.

**Pull request closed without merging**
