### PR TITLE
fix: add audio trim for pronunciation

### PR DESCRIPTION
**Pull request by kvdb**
To prevent a noticeable mouse click on recording start, use 100ms of
trimming at the beginning and 50ms out of safety, at the end.
A click at the beginning can disturb analysis a lot.

### CODE REVIEW

**Comment by kvdb** [comment]
Didn't check it locally, but if this works, same should be applied to recognition (API already supports it).

**Comment by joggienl** [comment]
This will not hold long. Especially not for recognition because that is already partially moved towards streaming audio. We can't use trim on streaming audio.

I think it might be better to adjust the recorder to apply a little delay somehow.

**Comment by kvdb** [comment]
That would also be a solution longer term indeed. Although we figured that not all frontends might be capable of audio processing, that's why we moved trim to backend.
Short term, it should get better demo results.

**Comment by joggienl** [comment]
> Although we figured that not all frontends might be capable of audio processing, that's why we moved trim to backend.

Can you explain what you mean by that?

**Comment by kvdb** [comment]
We were dealing with native audio recording capabilities of a mobile device at one time. Not sure if that's relevant today.

**Pull request closed without merging**
