### PR TITLE
refactor: untangle websockets

### PR DESCRIPTION
**Pull request by mthjs**
Trim down the floof around the websocket features by exposing them as
functions instead of methods.

Also document them more verbosely both inline and in the JSdocs.

### CODE REVIEW

**Comment by joggienl** [comment]
Food for thought: put the websocket stuf in its own file in stead of the more general/generic "communications" file?

**Comment by mthjs** [comment]
Yes, I could, but it also uses the same settings. Which would mean in turn that either the settings need to be exposed, or I need to keep settings for both modules. For now I think this will suffice

**Comment by remcohaszing** [comment]
By putting them in a single file, you enforce those that would only like to use the REST API wrapper to also pull in an autobahn dependency. I think that's quite a heavy dependency.

So I agree with @joggienl, this should be separated. I think there should be 3 files. One for settings, one for the REST stuff and one for the websocket communications.

I don't think it's a problem when the settings are exposed. They're either set by the user or the defaults, which can be simply copy-pasted if one would really want to access them.

**Comment by mthjs** [comment]
If there is no objection against exposing the settings then I'll change it

**Comment by mthjs** [comment]
On the other side, are we planning on making autobahn a peer-dependency? Otherwise it will get shipped with the SDK no matter what. I assume bundlers could ignore it in their builds if it lives in a separate file; but that also proves that the assumption is made that a bundler is used

**Pull request merged**
